import "./globals.css";
import { Inter } from 'next/font/google'
import Header from "./components/Header";
import { ShootingStars } from "@/components/ui/shooting-stars";
import { StarsBackground } from "@/components/ui/stars-background";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})



export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.variable} >
        <div className="min-h-screen bg-gradient-to-b from-[#1f0341] via-[#200650] to-[#1b074b] relative w-full text-white ">
          <div>
           <Header/>
             
            <StarsBackground className="pointer-events-none"/>
             <ShootingStars className="pointer-events-none" />
              {children}
    
          
          </div>
        </div>
      </body>
    </html>
  );
}
